"""empty message

Revision ID: 4c4191aaee90
Revises: 748269a10213
Create Date: 2026-02-10 02:23:49.082936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4191aaee90'
down_revision = '748269a10213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('town', sa.String(length=120), nullable=False),
    sa.Column('use', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_location',
    sa.Column('user.id', sa.Integer(), nullable=False),
    sa.Column('location.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location.id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user.id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user.id', 'location.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_location')
    op.drop_table('location')
    # ### end Alembic commands ###
